####################################
#
# Music Transformer
#
####################################
FROM ubuntu:latest as music_transformer_data
RUN apt-get update && apt-get install ca-certificates curl apt-transport-https ca-certificates gnupg -y && \
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
  tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
  apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
  apt-get update && apt-get install google-cloud-sdk -y
RUN mkdir -p /data/transformer && \
  gsutil -q -m cp -r gs://magentadata/models/music_transformer/* /data/transformer && \
  gsutil -q -m cp gs://magentadata/soundfonts/Yamaha-C5-Salamander-JNv5.1.sf2 /data/transformer

####################################
#
# Jason
#
####################################
FROM ubuntu:latest as jason

######### Install Python 3 and system packages #########
ENV LANG C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  libgirepository1.0-dev gcc libcairo2-dev \
  pkg-config gir1.2-gtk-3.0 software-properties-common \
  git wget curl \
  libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev \
  build-essential libssl-dev libffi-dev \
  && add-apt-repository ppa:deadsnakes/ppa -y \
  && apt-get install python3.6 python3-pip python-dev -y

# ######### jason data #########
# RUN git clone https://github.com/jason9693/MusicTransformer-tensorflow2.0.git /notebooks/MusicTransformer-tensorflow2.0
RUN pip3 install requests pycairo 
RUN pip3 install pygobject --ignore-installed
RUN pip3 install --upgrade setuptools
RUN pip3 install tqdm
# Transform requirements.txt
RUN git clone https://github.com/jason9693/MusicTransformer-tensorflow2.0.git /MusicTransformer-tensorflow2.0

# Fix requirements.txt file
RUN sed 's/^pygobject==.*/pygobject==3.36.0/g' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed 's/^tensorflow-gpu==.*/tensorflow-gpu==2.2.0rc4/g' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed '72d' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed '7d' /MusicTransformer-tensorflow2.0/requirements.txt -i


RUN pip3 install -r /MusicTransformer-tensorflow2.0/requirements.txt --ignore-installed
RUN git clone https://github.com/jason9693/midi-neural-processor.git \
  && mv midi-neural-processor /notebooks/MusicTransformer-tensorflow2.0/midi_processor
RUN sh /MusicTransformer-tensorflow2.0/dataset/scripts/classic_piano_downloader.sh /data/classic_piano
RUN python3 /MusicTransformer-tensorflow2.0/preprocess.py /data/classic_piano /data/classic_piano_processed

WORKDIR /notebooks/MusicTransformer-tensorflow2.0

####################################
#
# Cuda Container
#
####################################
FROM nvcr.io/nvidia/tensorflow:20.03-tf2-py3
ARG DEBIAN_FRONTEND=noninteractive

######### Magenta Data #########
# Copy Transformer
COPY --from=music_transformer_data /data /data
COPY --from=jason /data/classic_piano_processed /data/classic_piano_processed

######### Install Python 3 and system packages#########
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
  libgirepository1.0-dev gcc libcairo2-dev \
  pkg-config gir1.2-gtk-3.0 software-properties-common \
  git curl wget vim 
  # \
  # && add-apt-repository ppa:deadsnakes/ppa -y \
  # && apt-get install python3.6 python3-pip -y

# ######### Install dependencies for jason #########
# RUN git clone https://github.com/jason9693/MusicTransformer-tensorflow2.0.git /notebooks/MusicTransformer-tensorflow2.0
RUN pip3 install requests pycairo
RUN pip3 install pygobject --ignore-installed
# Transform requirements.txt
RUN apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev -y
RUN git clone https://github.com/jason9693/MusicTransformer-tensorflow2.0.git /notebooks/MusicTransformer-tensorflow2.0
# Fix requirements.txt file
RUN sed 's/^pygobject==.*/pygobject==3.36.0/g' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed 's/^tensorflow-gpu==.*/tensorflow-gpu==2.2.0rc4/g' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed '72d' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN sed '7d' /MusicTransformer-tensorflow2.0/requirements.txt -i
RUN pip3 install -r /notebooks/MusicTransformer-tensorflow2.0/requirements.txt --ignore-installed

######### Install Jupyter and Notebook requirements #########
RUN pip3 install google-colab jupyter tensor2tensor prompt-toolkit
# https://github.com/jupyter/jupyter_console/issues/163#issuecomment-418392676
RUN pip3 install --upgrade ipykernel
# Magenta runs an old version of bokeh
# RUN pip uninstall bokeh -y
# RUN pip3 install bokeh==1.4.0


######### Set up file system #########
RUN mkdir -p /notebooks && chmod a+rwx /notebooks
RUN mkdir -p /logs && chmod 777 /logs
RUN mkdir /.local && chmod a+rwx /.local
WORKDIR /notebooks
EXPOSE 8888
COPY jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

######### Install jason #########

RUN git clone https://github.com/jason9693/midi-neural-processor.git \
  && mv midi-neural-processor /notebooks/MusicTransformer-tensorflow2.0/midi_processor

# ######### CUDA #########
# RUN add-apt-repository ppa:graphics-drivers/ppa -y \
# && apt update
# # RUN apt install nvidia-390 -y
# RUN apt install nvidia-cuda-toolkit -y

WORKDIR /notebooks/MusicTransformer-tensorflow2.0

######### Run Jupyter notebook #########
# CMD ["bash", "-c", "jupyter notebook --ip 0.0.0.0 --allow-root --no-browser"]
